import { createContext } from "react";

export const ThemeColors = {
  primary: "#0B1C30",
  secondary: "#F5F5F5",
  secondaryBlack: "#787f86",
  light: "#E7E7E7",
  lightBlack: "#465567",
  other: "#7E7383",
  black: "#000000",
  white: "#FFFFFF",
  disable: "#8A9CB0",
  markdisable: "#84bef5",
  inputbg: "#FAFAFA",
  lightBlue: "#4FA4F4",
  skyBlue: "#F0F5FB",
  midBlue: "#C8E3F6",
  lightSkyBlue: "#ECF5FF",
  purple: "#575FCC",
  lightPurple: "#787f86",
  visited: "#739EF1",
  expired: "#D03D3D",
  lightExpired: "#FED3D3",
  inProgress: "#FABF48",
  completed: "#8AD0AF",
  lightCompleted: "#E7FFF3",
  notVisited: "#E3E9EE",
  lightGreen: "#EFFFF7",
  lightRed: "#FEE8E8",
  grey: "#ABB6C0",
  font: {
    cardheading: {
      fontSize: "20px",
      fontWeight: 500,
      lineHeight: "40px",
      color: "#0B1C30",
      fontFamily: "Medium",
    },
    categoryHeading: {
      fontSize: "14px",
      fontWeight: 400,
      lineHeight: "16px",
      color: "#787f86",
      fontFamily: "Medium",
    },
    RobotgoryHeading: {
      fontSize: "14px",
      fontWeight: 400,
      lineHeight: "30px",
      color: "#787f86",
      fontFamily: "Roboto",
    },
    RobotgoryPremiumVideoText: {
      fontSize: "15px",
      fontWeight: 400,
      lineHeight: "30px",
      color: "#000000",
      fontFamily: "Roboto",
    },
    RobotgoryHeadingText: {
      fontSize: "12px",
      fontWeight: 400,
      lineHeight: "14px",
      color: "#787f86",
      fontFamily: "Roboto",
      letterSpacing: "0.02em",
    },
    RobotgoryHeadingText1: {
      fontSize: "16px",
      fontWeight: 700,
      lineHeight: "19px",
      fontFamily: "Roboto",
      letterSpacing: "0.02em",
    },
    RobotLightHeading: {
      fontSize: "14px",
      fontWeight: 400,
      lineHeight: "16px",
      color: "#787f86",
      fontFamily: "Roboto",
    },
    RobotMediumHeading: {
      fontSize: "14px",
      fontWeight: 600,
      lineHeight: "16px",
      color: "#212730",
      fontFamily: "Roboto",
    },
    RobotSolMediumHeading: {
      fontSize: "14px",
      fontWeight: 600,
      lineHeight: "16px",
      color: "#000",
      fontFamily: "Roboto",
    },
    RobotSolMediumHeading1: {
      fontSize: "14px",
      fontWeight: 600,
      lineHeight: "16px",
      color: "#000",
      fontFamily: "Roboto",
    },
    RobotodesHeading: {
      fontSize: "24px",
      fontWeight: 500,
      lineHeight: "20px",
      color: "#000",
      fontFamily: "Roboto",
    },
    RobotoPrivacyHeading: {
      fontSize: "24px",
      fontWeight: 500,
      lineHeight: "28px",
      color: "#000000",
      fontFamily: "Roboto",
    },
    RobotoPrivacyHeading1: {
      fontSize: "26px",
      fontWeight: 700,
      lineHeight: "28px",
      color: "#000000",
      fontFamily: "Roboto",
    },
    RobotoPrivacyTitelHeading: {
      fontSize: "20px",
      fontWeight: 500,
      lineHeight: "23px",
      color: "#000000",
      fontFamily: "Roboto",
    },
    RobotoPrivacyTitelHeading1: {
      fontSize: "20px",
      fontWeight: 600,
      lineHeight: "23px",
      color: "#000000",
      fontFamily: "Roboto",
    },
    RobotoTitelHeading: {
      fontSize: "20px",
      fontWeight: 500,
      lineHeight: "20px",
      color: "#000",
      fontFamily: "Roboto",
    },
    CardSubHeading1: {
      fontSize: "20px",
      fontWeight: 500,
      lineHeight: "20px",
      color: "#787F86",
      fontFamily: "Roboto",
    },
    RobotoTextHeading: {
      fontSize: "14px",
      fontWeight: 500,
      lineHeight: "16px",
      color: "#485569",
      fontFamily: "Roboto",
    },
    SolutionRobotoTextHeading: {
      fontSize: "14px",
      fontWeight: 500,
      lineHeight: "16px",
      color: "#4FA4F4",
      fontFamily: "Roboto",
    },
    RobotoblackHeading: {
      fontSize: "16px",
      fontWeight: 500,
      lineHeight: "18px",
      color: "black",
      fontFamily: "Roboto",
    },
    RobotoblackHeading1: {
      fontSize: "16px",
      fontWeight: 500,
      lineHeight: "18px",
      color: "black",
      fontFamily: "Roboto",
    },
    priceHeading: {
      fontSize: "calc(12px + 0.5vmin)",
      fontWeight: 400,
      lineHeight: "23px",
      color: "#787f86",
      fontFamily: "Bold",
    },
    price: {
      fontSize: "calc(12px + 0.5vmin)",
      fontWeight: 400,
      lineHeight: "23px",
      color: "#4FA4F4",
      fontFamily: "Bold",
    },
    videoPrice: {
      fontSize: "18px",
      fontWeight: 700,
      lineHeight: "21px",
      color: "#4FA4F4",
      fontFamily: "Roboto",
    },
    videoPriceHeading: {
      fontSize: "14px",
      fontWeight: 400,
      lineHeight: "16px",
      color: "#787f86",
      fontFamily: "Roboto",
    },
    aboutText: {
      fontSize: "calc(4.72px + 2vmin)",
      lineHeight: "23px",
      fontFamily: "SemiBold",
      textTransform: "uppercase",
    },
    smallText: {
      fontSize: "10px",
      fontWeight: 400,
      fontFamily: "Roboto",
    },
    SmallHeading: {
      fontSize: "14px",
      fontWeight: 500,
      lineHeight: "16px",
      color: "#787f86",
      fontFamily: "Medium",
    },
    transactionText: {
      fontSize: "16px",
      fontWeight: 700,
      lineHeight: "19px",
      color: "#00000",
      fontFamily: "Roboto",
    },
    CorrectHeading: {
      fontSize: "14px",
      fontWeight: 500,
      lineHeight: "16px",
      color: "#787f86",
      fontFamily: "Medium",
    },
    TitleHeading: {
      fontSize: "16px",
      fontWeight: 500,
      lineHeight: "20px",
      color: "#0B1C30",
      fontFamily: "Medium",
    },
    smallTiHeading: {
      fontSize: "16px",
      fontWeight: 500,
      lineHeight: "20px",
      color: "#465567",
      fontFamily: "Medium",
    },
    NormalTitleHeading: {
      fontFamily: "Outfit",
      fontStyle: "normal",
      fontWeight: 400,
      fontSize: "16px",
      lineHeight: "20px",
      color: "#465567",
    },
    privacyHeading: {
      fontFamily: "Outfit",
      fontStyle: "normal",
      fontWeight: 400,
      fontSize: "16px",
      lineHeight: "20px",
      color: "#465567",
    },
    MidTitleHeading: {
      fontFamily: "Outfit",
      fontStyle: "normal",
      fontWeight: "600",
      fontSize: "18px",
      lineHeight: "20px",
      color: "#000000",
    },
    OverallTitleHeading: {
      fontFamily: "Outfit",
      fontStyle: "normal",
      fontWeight: "600",
      fontSize: "14px",
      lineHeight: "20px",
      color: "#000000",
    },
    ResultTitleHeading: {
      fontFamily: "Outfit",
      fontStyle: "normal",
      fontWeight: "600",
      fontSize: "24px",
      lineHeight: "30.24px",
      color: "#000000",
    },
    VideoTitleHeading: {
      fontFamily: "Outfit",
      fontStyle: "normal",
      fontWeight: "600",
      fontSize: "20px",
      lineHeight: "27px",
      color: "#000000",
    },

    tileHeading: {
      fontSize: "20px",
      fontWeight: 700,
      lineHeight: "16px",
      color: "#787f86",
    },

    NormalHeading: {
      fontSize: "14px",
      fontWeight: 600,
      fontFamily: "Medium",
    },
    AboutCard: {
      fontFamily: "Outfit",
      fontStyle: "normal",
      fontWeight: "400",
      fontSize: "14px",
      lineHeight: "20px",
      color: "#000000",
    },

    cardSubHeading: {
      fontSize: "calc(13px + 1.2vmin)",
      fontWeight: 600,
      lineHeight: "21px",
    },

    cardWalletHeading: {
      fontSize: "12px",
      fontWeight: 600,
      lineHeight: "14px",
    },
    addMoneyWalletHeading: {
      fontSize: "12px",
      fontWeight: 400,
      lineHeight: "14px",
      fontStyle: "normal",
    },
    subHeading: {
      fontSize: "20px",
      fontWeight: 500,
      lineHeight: "23px",
    },
    boldHeading: {
      fontSize: "20px",
      fontWeight: 600,
      lineHeight: "23px",
    },

    Heading: {
      fontSize: "calc(22px + 0.5vmin)",
      fontWeight: 500,
      lineHeight: "28px",
    },

    walletlargHeading: {
      fontFamily: "Regular",
      fontStyle: "Regular",
      fontWeight: 600,
      fontSize: "32px",
      lineHeight: "38px",
    },
    largHeading: {
      fontFamily: "Regular",
      fontStyle: "Regular",
      fontWeight: 400,
      fontSize: "32px",
      lineHeight: "40px",
    },
    mlargHeading: {
      fontFamily: "Regular",
      fontStyle: "Regular",
      fontWeight: 400,
      fontSize: "24px",
      lineHeight: "40px",
    },
    xLargHeading: {
      fontFamily: "Medium",
      fontWeight: 500,
      fontSize: "36px",
      lineHeight: "45px",
    },
    Heading14600: {
      fontFamily: "Medium",
      fontWeight: 600,
      fontSize: "calc(14px + 0.5vmin)",
    },
    Heading12500: {
      fontFamily: "Medium",
      fontWeight: 500,
      fontSize: "calc(11px + 0.5vmin)",
    },
    Heading24500: {
      fontFamily: "Outfit",
      fontWeight: 500,
      fontSize: "calc(22px + 0.9vmin)",
    },
  },
};

export const ThemeColorContext = createContext({
  color: ThemeColors.primary,
});

export default function ThemeColorWrapper() {}
